In [1]:
import numpy as np

In [2]:
# 행렬 코딩
A = np.array([[3,1,1], [1,-2,-1], [1,1,1]])

print(A)
print(A.shape)

[[ 3  1  1]
 [ 1 -2 -1]
 [ 1  1  1]]
(3, 3)


In [3]:
# 벡터 코딩
B = np.array([4,1,2])

print(B)
print(B.shape)

[4 1 2]
(3,)


In [4]:
# 역행렬 구하기
A_inv = np.linalg.inv(A)

print(A_inv)
print(A_inv.shape)

[[ 5.00000000e-01 -7.40148683e-17 -5.00000000e-01]
 [ 1.00000000e+00 -1.00000000e+00 -2.00000000e+00]
 [-1.50000000e+00  1.00000000e+00  3.50000000e+00]]
(3, 3)


In [5]:
# 역행렬을 이용한 선형 시스템 Ax = B의 해 구하기
x = A_inv @ B

print(x)
print(x.shape)

[ 1. -1.  2.]
(3,)


In [6]:
# 결과 검증
bb = A @ x

print(bb.shape)
print(bb)

if np.linalg.norm(B - bb) < 1e-3:
  print('OK')
else:
  print('wrong')

(3,)
[4. 1. 2.]
OK
