In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

tensor는 numpy의 ndarray와 유사하며, 추가로 GPU를 사용한 연산 가속도 가능

In [ ]:
from __future__ import print_function
import torch

torch.__version__

'1.10.0+cu111'

초기화되지 않은 5x3 행렬을 생성

In [ ]:
x = torch.empty(5, 3)
print(x)

tensor([[-1.2241e-20,  3.0751e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  6.4460e-44],
        [ 1.1578e+27,  1.1362e+30,  7.1547e+22],
        [ 4.5828e+30,  1.2121e+04,  7.1846e+22],
        [ 9.2198e-39,  7.0374e+22,  0.0000e+00]])


무작위로 초기화된 행렬을 생성

In [ ]:
x = torch.randn(5, 3) # 정규분포를 따르는 값
print(x)

x = torch.rand(5, 3) # 0~1사이의 값
print(x)

tensor([[ 0.6562,  0.2831,  0.7069],
        [-0.5802, -1.5207, -1.3746],
        [-0.6691,  0.3186, -1.0087],
        [-0.7056,  0.9598, -2.4161],
        [ 0.4935, -1.0390, -1.0935]])
tensor([[0.4034, 0.2549, 0.6420],
        [0.0762, 0.9919, 0.9983],
        [0.0918, 0.8062, 0.0616],
        [0.1494, 0.5607, 0.2728],
        [0.7415, 0.8606, 0.9963]])


dtype가 long이고 0으로 채워진 행렬을 생성

In [ ]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [ ]:
x = torch.ones(5, 3, dtype=torch.long)
x

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

데이터로부터 tensor를 직접 생성

In [ ]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [ ]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [ ]:
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[ 0.2827, -1.1278, -1.0413],
        [-0.6309,  0.6726, -1.7871],
        [-1.3497,  0.2741, -0.1825],
        [-2.0894,  2.1170, -1.0108],
        [ 1.6670, -0.4657, -0.6231]])

In [ ]:
# 행렬의 크기를 출력
x.size(), x.shape

(torch.Size([5, 3]), torch.Size([5, 3]))

In [ ]:
# 행렬의 합 구하기
y = torch.rand(5, 3)
x, y, x + y

(tensor([[ 0.2827, -1.1278, -1.0413],
         [-0.6309,  0.6726, -1.7871],
         [-1.3497,  0.2741, -0.1825],
         [-2.0894,  2.1170, -1.0108],
         [ 1.6670, -0.4657, -0.6231]]), tensor([[0.7480, 0.1530, 0.6381],
         [0.6785, 0.0325, 0.8692],
         [0.2949, 0.9499, 0.6935],
         [0.0390, 0.8910, 0.3269],
         [0.6236, 0.2055, 0.6192]]), tensor([[ 1.0307, -0.9749, -0.4032],
         [ 0.0475,  0.7051, -0.9179],
         [-1.0548,  1.2240,  0.5110],
         [-2.0504,  3.0080, -0.6839],
         [ 2.2906, -0.2601, -0.0038]]))

In [ ]:
# add함수를 이용해 행렬의 합 구하기
torch.add(x, y)

tensor([[ 1.0307, -0.9749, -0.4032],
        [ 0.0475,  0.7051, -0.9179],
        [-1.0548,  1.2240,  0.5110],
        [-2.0504,  3.0080, -0.6839],
        [ 2.2906, -0.2601, -0.0038]])

In [ ]:
result = torch.empty(5, 3)
print(result)

torch.add(x, y, out=result)
print(result)

tensor([[-2.0642e-20,  3.0751e-41,  4.4842e-44],
        [ 0.0000e+00,         nan,  0.0000e+00],
        [ 1.0948e+21,  9.2868e-04,  1.3556e-19],
        [ 9.8864e-33,  1.0008e+01,  1.4790e+20],
        [ 9.3175e-39,  0.0000e+00,  0.0000e+00]])
tensor([[ 1.0307, -0.9749, -0.4032],
        [ 0.0475,  0.7051, -0.9179],
        [-1.0548,  1.2240,  0.5110],
        [-2.0504,  3.0080, -0.6839],
        [ 2.2906, -0.2601, -0.0038]])


덧셈 in-place 방식

In [ ]:
# adds x to y
print(y)
y.add_(x)
y

tensor([[0.7480, 0.1530, 0.6381],
        [0.6785, 0.0325, 0.8692],
        [0.2949, 0.9499, 0.6935],
        [0.0390, 0.8910, 0.3269],
        [0.6236, 0.2055, 0.6192]])


tensor([[ 1.0307, -0.9749, -0.4032],
        [ 0.0475,  0.7051, -0.9179],
        [-1.0548,  1.2240,  0.5110],
        [-2.0504,  3.0080, -0.6839],
        [ 2.2906, -0.2601, -0.0038]])

In-place방식으로 tensor의 값을 변경하는 경우 연산은 _를 접미사로 갖는다.  
ex) x.copy_(y), x.t_()는 x를 변경한다.  
Numpy스러운 인덱싱 표기 방법을 사용할 수도 있다.

In [ ]:
print(x)
print(x[:, 1])

tensor([[ 0.2827, -1.1278, -1.0413],
        [-0.6309,  0.6726, -1.7871],
        [-1.3497,  0.2741, -0.1825],
        [-2.0894,  2.1170, -1.0108],
        [ 1.6670, -0.4657, -0.6231]])
tensor([-1.1278,  0.6726,  0.2741,  2.1170, -0.4657])


크기 변경: tensor의 크기나 모양을 변경하고 싶다면 torch.view를 사용

In [ ]:
x = torch.randn(4, 4)
print(x,'\n')

y = x.view(16) # 16개의 차원을 가진 벡터의 형태로 reshape
z = x.view(-1, 2) # 
print(y, '\n\n', z, '\n')
y.size(), z.size()

tensor([[ 0.6953,  0.3565,  1.5707,  1.3330],
        [ 0.0472,  0.3566,  0.2431, -0.1621],
        [ 0.5452,  0.4852, -0.7454,  1.6493],
        [ 0.6262,  0.9306,  0.5443, -0.0787]]) 

tensor([ 0.6953,  0.3565,  1.5707,  1.3330,  0.0472,  0.3566,  0.2431, -0.1621,
         0.5452,  0.4852, -0.7454,  1.6493,  0.6262,  0.9306,  0.5443, -0.0787]) 

 tensor([[ 0.6953,  0.3565],
        [ 1.5707,  1.3330],
        [ 0.0472,  0.3566],
        [ 0.2431, -0.1621],
        [ 0.5452,  0.4852],
        [-0.7454,  1.6493],
        [ 0.6262,  0.9306],
        [ 0.5443, -0.0787]]) 



(torch.Size([16]), torch.Size([8, 2]))

In [ ]:
# 만약 tensor에 하나의 값만 존재한다면, .item()을 사용하여 숫자값을 얻을 수 있다.

x = torch.randn(1)
print(x)
print(type(x), type(x.item()))
x.item()

tensor([-0.3052])
<class 'torch.Tensor'> <class 'float'>


-0.30522996187210083

## Numpy 변환(Bridge)  
Torch Tensor를 Numpy 배열로 변환하거나 그 반대로 하는것은 간단하다.  
(CPU)상의 Torch Tensor와 Numpy배열은 저장 공간을 공유하기 때문에, 하나를 변경한다면 나머지 하나도 변경된다.
- Torch tensor를 Numpy배열로 변경하기

In [ ]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [ ]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [ ]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
temp = a.clone()
temp_numpy = temp.numpy()

a.add_(1)
print(a)
print(temp_numpy)

tensor([3., 3., 3., 3., 3.])
[2. 2. 2. 2. 2.]


In [ ]:
import numpy as np

a = np.ones(5)
print(a)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CharTensor를 제외한 CPU상의 모든 Tensor는 Numpy로의 변환을 지원하며 반대의 변환 또한 가능하다.

## CUDA Tensors
- .to 메소드를 사용하여 Tensor를 어떤 장치로 옮길 수 있다.

In [ ]:
x = torch.rand(4, 4)
if torch.cuda.is_available():
  device = "cuda:0" # torch.device('cuda:0)
  y = torch.ones_like(x, device=device) # GPU상에 직접적으로 tensor를 생성
  print(y)

  x = x.to(device) # to()를 사용하여 x를 GPU로 옮김
  z = x + y
  print(z)
  print(z.to('cpu', torch.double)) # CPU로 옮기는 것도 가능

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')
tensor([[1.5593, 1.2231, 1.6611, 1.0783],
        [1.7037, 1.5403, 1.6234, 1.5067],
        [1.5541, 1.9857, 1.5250, 1.7540],
        [1.7349, 1.3010, 1.9187, 1.4776]], device='cuda:0')
tensor([[1.5593, 1.2231, 1.6611, 1.0783],
        [1.7037, 1.5403, 1.6234, 1.5067],
        [1.5541, 1.9857, 1.5250, 1.7540],
        [1.7349, 1.3010, 1.9187, 1.4776]], dtype=torch.float64)


In [ ]:
x = x.cuda()