In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.7.0'

### 변수 생성

In [4]:
# 모양이 [1, 2, 3] 이고 값은 0으로 채워진 3차원 tensor를 생성

my_variable = tf.Variable(tf.zeros([1,2,3]))
my_variable

<tf.Variable 'Variable:0' shape=(1, 2, 3) dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

### 변수의 사용

In [7]:
# 텐서플로우 그래프에서 tf.Variable의 값을 사용하려면 이를 단순히 tf.Tensor로 취급하면 된다.
v = tf.Variable(0.0)
print(v)

w = v + 1 # w는 v값 기준으로 계산되는 tf.Tensor이다.
w

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.0>


<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

변수가 수식에 사용될 때 변수는 자동적으로 tf.Tensor로 변환되어 값을 표현한다.

In [9]:
# 값을 변수에 할당하려면 assign, assign_add 메소드와 tf.Variable 클래스에 존재하는 메소드를 사용
a = tf.Variable(0.0)
a.assign_add(1)
a.read_value()

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

### tf.Tensor 객체의 랭크는 그 차원의 수

In [14]:
# 랭크 0
mammal = tf.Variable('코끼리', tf.string)
ignition = tf.Variable(451, tf.int16)
floating = tf.Variable(3.145, tf.float64)
its_complicated = tf.Variable(12.3 - 4.58j, tf.complex64)

mammal, ignition, floating, its_complicated

(<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'\xec\xbd\x94\xeb\x81\xbc\xeb\xa6\xac'>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=451>,
 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.145>,
 <tf.Variable 'Variable:0' shape=() dtype=complex128, numpy=(12.3-4.58j)>)

In [15]:
# 랭크 1
mystr = tf.Variable(['안녕하세요'], tf.string)
cool_numbers = tf.Variable([3,13, 451234], tf.float32)
first_primes = tf.Variable([2, 3, 5, 7, 11], tf.int32)
its_very_complicated = tf.Variable([12.3 - 4.85j, 7.5 - 6.23j], tf.complex64)

mystr, cool_numbers, first_primes, its_very_complicated

(<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=
 array([b'\xec\x95\x88\xeb\x85\x95\xed\x95\x98\xec\x84\xb8\xec\x9a\x94'],
       dtype=object)>,
 <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([     3,     13, 451234], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([ 2,  3,  5,  7, 11], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=complex128, numpy=array([12.3-4.85j,  7.5-6.23j])>)

In [19]:
from re import M
# 고차원 랭크
mymat = tf.Variable([[11], [7]], tf.int16)
myxor = tf.Variable([[False, True], [True, True]], tf.bool)
linear_squares = tf.Variable([[4], [9], [16], [25]], tf.int32)

# tf.rank: 객체의 랭크 구하기
rank_of_squares = tf.rank(linear_squares)
mymatC = tf.Variable([[7], [11]], tf.int32)

print(mymat)
print(rank_of_squares)

<tf.Variable 'Variable:0' shape=(2, 1) dtype=int32, numpy=
array([[11],
       [ 7]], dtype=int32)>
tf.Tensor(2, shape=(), dtype=int32)


In [20]:
my_image = tf.zeros([10, 299, 299, 3]) # 배치 * 높이 * 너비 * 색상

# H*W = 299 * 299

In [22]:
r = tf.rank(my_image)
print(r)

tf.Tensor(4, shape=(), dtype=int32)


### tf.Tensor 원소 참조하기

In [23]:
my_vector = tf.Variable([1, 2, 3, 4], tf.int32)
print(tf.rank(my_vector))

tf.Tensor(1, shape=(), dtype=int32)


In [24]:
my_scalar = my_vector[2]
print(my_scalar)

tf.Tensor(3, shape=(), dtype=int32)


In [27]:
squarish_squares = tf.Variable([[4, 9], [16, 25]], tf.int32)
my_scalar = squarish_squares[1, 0]

print(squarish_squares)
print(my_scalar)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[ 4,  9],
       [16, 25]], dtype=int32)>
tf.Tensor(16, shape=(), dtype=int32)


In [28]:
my_row_vector = squarish_squares[1]
my_column_vector = squarish_squares[:, 1]
print(squarish_squares)
print(my_row_vector)
print(my_column_vector)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[ 4,  9],
       [16, 25]], dtype=int32)>
tf.Tensor([16 25], shape=(2,), dtype=int32)
tf.Tensor([ 9 25], shape=(2,), dtype=int32)


### tf.Tensor 객체 형태 얻기

In [31]:
zeros = tf.zeros(squarish_squares.shape) # squarish_squares의 shape로 새로운 tensor 생성
zeros

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

### tf.Tensor 형태 변경

In [36]:
#60
rank_three_tensor = tf.ones([3, 4, 5])
print(rank_three_tensor.shape)
print(rank_three_tensor)

matrix = tf.reshape(rank_three_tensor, [6, 10]) # 기존 tensor를 6*10 행렬로 형태를 변경
print(matrix.shape)

matrixB = tf.reshape(matrix, [3, -1]) # 기존 내용을 3*20 형태로 변경
print(matrixB.shape)

matrixAlt = tf.reshape(matrixB, [4, 3, -1])
print(matrixAlt.shape)

(3, 4, 5)
tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 4, 5), dtype=float32)
(6, 10)
(3, 20)
(4, 3, 5)


### 자료형

In [40]:
# 정수형 tensor를 실수형으로 변환
a = tf.constant([1, 2, 3])
print(a)

float_tensor = tf.cast(tf.constant([1, 2, 3]), dtype=tf.float32)
float_tensor

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>